### ISSUE TITLE
Testing via `python3 setup.py test` fails

### ISSUE THREAD

**Issue by PhilipHildebrand** [precice/fenicsx-adapter#16] opened 2022-12-15 19:05 UTC
Executing the tests/test suites individually does work, but using `python3 setup.py test` results in this error:

```
ERROR: XML parser was unable to open configuration file "/home/philip/Schreibtisch/fenicsx-adapter fork/fenicsx-adapter/tests/dummy.xml"
```

**Comment by BenjaminRodenberg** [comment] 2022-12-16 16:03
What's interesting: Our tests in the CI Pipeline seem to work (see https://github.com/precice/fenicsx-adapter/actions/runs/3696371322/jobs/6259975439). Did you try to run the commands that our CI pipeline uses?

https://github.com/precice/fenicsx-adapter/blob/5d70f0242b356a9509655f1d0065e2a84291587e/.github/workflows/build-and-test.yml#L41-L44

Another thing that would be interesting for further debugging is to run `python3 setup.py test`  in the CI pipeline.

**Comment by BenjaminRodenberg** [comment] 2022-12-16 18:14
Just checked running `python3 setup.py test` on my local system using 9e6510aad549a59cf3e57d5d94173e0bbd647638 and everything worked as expected. Since this is also not reproducible with the CI pipeline, I will close this issue. @PhilipHildebrand: For your local setup you have a work-around, so there is no need for further investigating this issue, correct?

**Closed by BenjaminRodenberg** 2022-12-16 18:14 UTC
Labels: bug

**Comment by PhilipHildebrand** [comment] 2022-12-17 13:01
> What's interesting: Our tests in the CI Pipeline seem to work (see https://github.com/precice/fenicsx-adapter/actions/runs/3696371322/jobs/6259975439). Did you try to run the commands that our CI pipeline uses?
> 
> https://github.com/precice/fenicsx-adapter/blob/5d70f0242b356a9509655f1d0065e2a84291587e/.github/workflows/build-and-test.yml#L41-L44
> 
> Another thing that would be interesting for further debugging is to run `python3 setup.py test` in the CI pipeline.

Running these commands does work, so I don't think we have to pursue this further.
